### ISSUE TITLE
Which CUDA version

### ISSUE THREAD

**Issue by nitinmukesh** [X-LANCE/AniTalker#16]
After installation torch is installed without CUDA. Please confirm the CUDA version it need.
Like
cu117
cu118
cu121

**Comment by liutaocode** [comment]
Hi. 
[python pytorch]
torch.version.cuda: 11.1 

[nvidia-smi]
Driver Version: 550.78
CUDA Version: 12.4

**Comment by nitinmukesh** [comment]
@liutaocode 

Thank you.

I request you to please provide the version of the following. I am struggling from last 15 minutes but getting 1 or the other error.

pip list will help

torch 
torchvision 
torchaudio

**Comment by nitinmukesh** [comment]
@liutaocode 

I tried this as per the instructions in Readme and requirements.txt

```
(anitalker) C:\usable\AniTalker>pip install torch==1.8.0+cu111 torchvision==0.9.0+cu111 torchaudio==0.8.0+cu111 --index-url https://download.pytorch.org/whl/cu111
Looking in indexes: https://download.pytorch.org/whl/cu111, https://pypi.ngc.nvidia.com
Collecting torch==1.8.0+cu111
  Downloading https://download.pytorch.org/whl/cu111/torch-1.8.0%2Bcu111-cp39-cp39-win_amd64.whl (3055.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 GB 12.3 MB/s eta 0:00:00
Collecting torchvision==0.9.0+cu111
  Downloading https://download.pytorch.org/whl/cu111/torchvision-0.9.0%2Bcu111-cp39-cp39-win_amd64.whl (1.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 20.3 MB/s eta 0:00:00
ERROR: Could not find a version that satisfies the requirement torchaudio==0.8.0+cu111 (from versions: 0.7.1, 0.7.2, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.10.0+cu111, 0.10.1+cu111, 0.10.2+cu111)
ERROR: No matching distribution found for torchaudio==0.8.0+cu111
```

**Comment by liutaocode** [comment]
So sorry. 

We have tested the installation process on Ubuntu 22.04 with the conda environment.

Here is the full list, some packages may not be used.

```
Package                 Version
----------------------- ---------------
absl-py                 2.1.0
aiohttp                 3.9.5
aiosignal               1.3.1
albucore                0.0.9
albumentations          1.4.8
annotated-types         0.7.0
antlr4-python3-runtime  4.9.3
async-timeout           4.0.3
attrs                   23.2.0
audioread               3.0.1
certifi                 2024.2.2
cffi                    1.16.0
charset-normalizer      3.3.2
ci-sdr                  0.0.2
click                   8.1.7
coloredlogs             15.0.1
ConfigArgParse          1.7
ctc_segmentation        1.7.4
Cython                  3.0.10
decorator               4.4.2
Distance                0.1.3
editdistance            0.8.1
einops                  0.8.0
espnet                  202301
espnet-tts-frontend     0.0.3
fast-bss-eval           0.1.3
filelock                3.14.0
flatbuffers             24.3.25
frozenlist              1.4.1
fsspec                  2024.3.1
g2p-en                  2.1.0
grpcio                  1.63.0
h5py                    3.11.0
hdf5storage             0.1.19
humanfriendly           10.0
hydra-core              1.3.2
idna                    3.7
imageio                 2.34.1
imageio-ffmpeg          0.4.9
importlib-metadata      4.13.0
inflect                 7.2.1
jaconv                  0.3.4
jamo                    0.4.1
joblib                  1.4.2
kaldiio                 2.18.0
lazy_loader             0.4
librosa                 0.10.2
llvmlite                0.42.0
Markdown                3.6
MarkupSafe              2.1.5
mkl-fft                 1.3.1
mkl-random              1.2.2
mkl-service             2.4.0
more-itertools          10.2.0
moviepy                 1.0.3
mpmath                  1.3.0
msgpack                 1.0.8
multidict               6.0.5
networkx                3.2.1
nltk                    3.8.1
numba                   0.59.1
numpy                   1.26.4
olefile                 0.47
omegaconf               2.3.0
onnx                    1.16.1
onnxruntime             1.18.0
opencv-python           4.10.0.82
opencv-python-headless  4.10.0.82
opt-einsum              3.3.0
packaging               24.0
pandas                  2.2.2
pillow                  10.3.0
pip                     23.3.1
platformdirs            4.2.1
pooch                   1.8.1
proglog                 0.1.10
protobuf                5.27.1
pybind11                2.10.3
pycparser               2.22
pydantic                2.7.3
pydantic_core           2.18.4
pyDeprecate             0.3.2
pypinyin                0.44.0
python-dateutil         2.9.0.post0
python-speech-features  0.6
pytorch-lightning       1.6.5
pytorch-wpe             0.0.1
pytz                    2024.1
pyworld                 0.3.4
PyYAML                  6.0.1
regex                   2024.4.28
requests                2.31.0
scikit-image            0.22.0
scikit-learn            1.4.2
scipy                   1.13.0
sentencepiece           0.2.0
setuptools              68.2.2
six                     1.16.0
soundfile               0.12.1
soxr                    0.3.7
sympy                   1.12.1
tensorboard             2.16.2
tensorboard-data-server 0.7.2
threadpoolctl           3.5.0
tifffile                2024.5.22
tomli                   2.0.1
torch                   1.8.0
torch-complex           0.4.3
torchaudio              0.8.0a0+a751e1d
torchlm                 0.1.6.10
torchmetrics            0.5.0
torchvision             0.9.0
tqdm                    4.66.4
typeguard               4.2.1
typing_extensions       4.11.0
tzdata                  2024.1
Unidecode               1.3.8
urllib3                 2.2.1
Werkzeug                3.0.3
wheel                   0.43.0
yarl                    1.9.4
zipp                    3.18.1

```

**Comment by liutaocode** [comment]
It's possible that the version I installed is quite old, and pip no longer provides it. We have also tested the inference process on torch version '2.3.1'. We will subsequently check a newer version and update the installation environment.

**Comment by nitinmukesh** [comment]
@liutaocode 
Thank you. I installed it.

Now a new error

```
(anitalker) C:\usable\AniTalker>python ./code/demo.py --infer_type 'mfcc_pose_only' --stage1_checkpoint_path 'ckpts/stage1.ckpt' --stage2_checkpoint_path 'ckpts/stage2_pose_only_mfcc.ckpt' --test_image_path 'test_demos/portraits/monalisa.jpg' --test_audio_path 'test_demos/audios/monalisa.wav' --result_path 'outputs/monalisa_mfcc/' --control_flag --seed 0 --pose_yaw 0.25 --pose_pitch 0 --pose_roll 0
HAL layer is enabled!
Traceback (most recent call last):
  File "C:\usable\AniTalker\code\demo.py", line 262, in <module>
    main(args)
  File "C:\usable\AniTalker\code\demo.py", line 65, in main
    lia.load_lightning_model(args.stage1_checkpoint_path)
  File "C:\usable\AniTalker\code\LIA_Model.py", line 26, in load_lightning_model
    state = torch.load(lia_pretrained_model_path, map_location='cpu')
  File "C:\Users\nitin\miniconda3\envs\anitalker\lib\site-packages\torch\serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\nitin\miniconda3\envs\anitalker\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\nitin\miniconda3\envs\anitalker\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: "'ckpts/stage1.ckpt'"
```

**Comment by nitinmukesh** [comment]
Fixed issues. Very difficult to run in windows.
